---
title: "title"
subtitle: "subtitle"
author: "Kim Dill-McFarland, kadm@uw.edu"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
date: "version `r format(Sys.time(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
---
# Background

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(cowplot)
#Create 'not in' operator
`%notin%` <- Negate(`%in%`)
```

# Data

Convert raw counts to tsv

```{r}
#Raw counts table
read_csv("data_raw/Hawn_UgandaMacrophage_counts.csv") %>% 
  rename(geneName=X1) %>% 
  write_tsv("data_raw/Hawn_UgandaMacrophage_counts.tsv")

read_csv("data_raw/Hawn_UgandaValidation_counts.csv") %>% 
  rename(geneName=X1) %>% 
  write_tsv("data_raw/Hawn_UgandaValidation_counts.tsv")
```

# Scaden

```{bash eval=FALSE}
#Instal scaden
pip install scaden

#Setup project dir
mkdir -p cell_deconvolution/
sudo chmod 777 -R cell_deconvolution/
cd cell_deconvolution/

#Get PBMC reference data
wget https://ndownloader.figshare.com/files/15008006 -O pbmc_data.h5ad

#Process ref and data overlap
##Ignore warnings. Not using GPU
scaden process pbmc_data.h5ad ../data/Hawn_UgandaMacrophage_counts.tsv

Found 11317 common genes.
Pre-processing raw data ...
Subsetting genes ...
Scaling using log_min_max
Writing to disk ...
Data pre-processing done.

mv processed.h5ad processed_orig.h5ad

#Train ref data
##Ignore warnings. Not using GPU
scaden train processed_orig.h5ad --steps 5000 --model_dir model_orig

#Predict cell %
scaden predict --model_dir model_orig ../data/Hawn_UgandaMacrophage_counts.tsv
mv scaden_predictions.txt scaden_predictions_orig.txt
```

```{bash eval=FALSE}
#Process ref and data overlap
##Ignore warnings. Not using GPU
scaden process pbmc_data.h5ad ../data/Hawn_UgandaValidation_counts.tsv

Found 11305 common genes.
Pre-processing raw data ...
Subsetting genes ...
Scaling using log_min_max
Writing to disk ...
Data pre-processing done.

mv processed.h5ad processed_valid.h5ad

#Train ref data
##Ignore warnings. Not using GPU
scaden train processed_valid.h5ad --steps 5000 --model_dir model_valid

#Predict cell %
scaden predict --model_dir model_valid ../data/Hawn_UgandaValidation_counts.tsv
mv scaden_predictions.txt scaden_predictions_valid.txt
```

## Cell predictions

```{r echo=FALSE, message=FALSE}
attach("data_clean/RSTR_RNAseq_data_combined_uniqueFULLID.RData")

cells <- read_tsv("results/cell_deconvolution/scaden_predictions_orig.txt") %>% 
  mutate(experiment="original") %>% 
  bind_rows(read_tsv("results/cell_deconvolution/scaden_predictions_valid.txt")) %>% 
  mutate(experiment= ifelse(is.na(experiment),"validation",experiment)) %>% 
  #Add metadata
  separate(X1, into=c("RS_SUB_ACCESSION_NO","condition"), sep="_|-", remove = FALSE) %>% 
  #add addtl metadata
  left_join(read_csv("data_raw/2020.11.20RSTR_Hawn_metadata.csv")) %>% 
  #Remove samples not in final dataset
  mutate(libID = gsub("-","_",toupper(X1))) %>% 
  inner_join(select(dat.combined.voom$targets,libID,experiment)) %>% 
  arrange(libID)
```

```{r echo=FALSE, fig.width=8.5}
plot1 <- cells %>% 
  select(FULLIDNO, Sample_Group, experiment, condition:CD8Tcells) %>% 
  pivot_longer(-c(FULLIDNO:condition)) %>% 
  filter(Sample_Group=="LTBI") %>% 
  
  ggplot(aes(x=condition, y=value, fill=name)) +
  geom_bar(position="fill", stat="identity") +
  
  ggh4x::facet_nested(Sample_Group~experiment+FULLIDNO, scales="free") +
  theme_classic() +
  labs(x="", y="Proportion of cells", fill="Cell type") +
  theme(legend.position = "bottom")

plot2 <- cells %>% 
  select(FULLIDNO, Sample_Group, experiment, condition:CD8Tcells) %>% 
  pivot_longer(-c(FULLIDNO:condition)) %>% 
  filter(Sample_Group=="RSTR") %>% 
  
  ggplot(aes(x=condition, y=value, fill=name)) +
  geom_bar(position="fill", stat="identity") +
  
  ggh4x::facet_nested(Sample_Group~experiment+FULLIDNO, scales="free") +
  theme_classic() +
  labs(x="", y="Proportion of cells", fill="Cell type") +
  theme(legend.position = "bottom")


plot1
plot2

ggsave("figs/cell_deconvolution.png", plot_grid(plot1,plot2, ncol=1),
       height=9, width=20)
```

# R session

```{r}
sessionInfo()
```

***