---
title: "title"
subtitle: "subtitle"
author: "Kim Dill-McFarland, kadm@uw.edu"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
date: "version `r format(Sys.time(), '%B %d, %Y')`"
editor_options: 
  chunk_output_type: console
---
# Background

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(cowplot)

`%notin%` <- Negate(`%in%`)
```

# Data

Convert raw counts table to tsv

```{r}
#Raw counts table
readRDS("data_raw/Hawn_SAMacrophage_counts.rds") %>% 
  as.data.frame() %>% 
  rownames_to_column("geneName") %>% 
  write_tsv("data_raw/Hawn_SAMacrophage_counts.txt")
```

# Scaden

```{bash eval=FALSE}
#Instal scaden
pip install scaden

#Setup project dir
mkdir -p cell_deconvolution/
sudo chmod 777 -R cell_deconvolution/
cd cell_deconvolution/

#Get PBMC reference data
wget https://ndownloader.figshare.com/files/15008006 -O pbmc_data.h5ad

#Process ref and data overlap
##Ignore warnings. Not using GPU
scaden process pbmc_data.h5ad ../data/Hawn_SAMacrophage_counts.txt 

Found 11325 common genes.
Pre-processing raw data ...
Subsetting genes ...
Scaling using log_min_max
Writing to disk ...
Data pre-processing done.

#Train ref data
##Ignore warnings. Not using GPU
scaden train processed.h5ad --steps 5000 --model_dir model

#Predict cell %
scaden predict --model_dir model ../data/Hawn_SAMacrophage_counts.txt 
```

## Cell predictions

```{r echo=FALSE, message=FALSE}
cells <- read_tsv("results/cell_deconvolution/RSTR_SAfrica_scaden_predictions.txt") %>% 
  #Add metadata
  separate(X1, into=c("FULLIDNO","condition"), sep="_", remove = FALSE) %>% 
  #add addtl metdata
  left_join(read_csv("data_raw/2020.11.05SA.RSTR_Hawn_metadata.csv"),
            by = c("FULLIDNO"="ptID")) %>% 
  #Fill in missing RSTR
  mutate(Sample_Group = ifelse(is.na(Sample_Group) & status == "control",
                               "LTBI",
                               ifelse(is.na(Sample_Group) & status == "case",
                               "RSTR", Sample_Group))) %>% 
  dplyr::rename(libID=X1) %>% 
  arrange(libID) %>% 
  #Rm white participants
  filter(ethnic != "White/European") %>%
  #Rm converters
  filter(FULLIDNO %notin% c("890-01347-2", "890-01612-7", 
                            "890-00658-6", "890-00798-1")) 
```

```{r echo=FALSE}
plot1 <- cells %>% 
  select(FULLIDNO, Sample_Group, condition:CD8Tcells) %>% 
  pivot_longer(-c(FULLIDNO:condition)) %>% 
  filter(Sample_Group=="LTBI") %>% 
  
  ggplot(aes(x=condition, y=value, fill=name)) +
  geom_bar(position="fill", stat="identity") +
  
  facet_grid(Sample_Group~FULLIDNO, scales="free") +
  theme_classic() +
  labs(x="", y="Proportion of cells", fill="Cell type")

plot2 <- cells %>% 
  select(FULLIDNO, Sample_Group, condition:CD8Tcells) %>% 
  pivot_longer(-c(FULLIDNO:condition)) %>% 
  filter(Sample_Group=="RSTR") %>% 
  
  ggplot(aes(x=condition, y=value, fill=name)) +
  geom_bar(position="fill", stat="identity") +
  
  facet_grid(Sample_Group~FULLIDNO, scales="free") +
  theme_classic() +
  labs(x="", y="Proportion of cells", fill="Cell type")

plot1
plot2

ggsave("figs/cell_deconvolution.png", plot_grid(plot1,plot2, ncol=1),
       height=8, width=20)
```

# R session

```{r}
sessionInfo()
```

***